# Generated by Django 5.0.4 on 2024-04-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_product_pricetimeline_priceupdate_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceupdate',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
