# Generated by Django 5.0.4 on 2024-04-20 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceupdate',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
