# Generated by Django 5.0.4 on 2024-04-20 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_trackedproducts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
