# Generated by Django 5.0.4 on 2024-04-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedproducts',
            name='url',
            field=models.URLField(default='', unique=True),
            preserve_default=False,
        ),
    ]
